Concurrent calls to RemoteService should not result in an exception